files:
  include: "assets/sass/**/*.s+(a|c)ss"
  ignore:
    - node_modules/**
    - assets/sass/utilities/**
    - assets/sass/vendor/**
syntax:
  include:
    - scss
    - sass
resolvers:
  property-sort-order: 1
  attribute-quotes: 0
  border-zero: 0
  no-color-keywords: 0
  no-css-comments: 0
  no-important: 0
  no-trailing-zero: 0
  space-after-bang: 0
  space-before-bang: 0
  space-after-colon: 0
  space-before-colon: 0
  hex-length: 0
  empty-line-between-blocks: 0
  url-quotes: 0
  zero-unit: 0
  hex-notation: 0
  indentation: 0
  final-newline: 0
options:
  optOut: false